server:
  error:
    include-stacktrace: on-param

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:3306/anime'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver